### ISSUE TITLE
Battery (showing  2 batteries)

### ISSUE THREAD

**Issue by danger44** [kfechter/LegionY530Ubuntu#105]
I am facing very low battery backup on ubuntu 18.04 LTS from the beginning. I have observed that sometimes it shows two batteries. So, when it gets fully charged then sometimes it switches to 2nd battery. Also, when the battery gets to low around 41% then it all sudden it change to 0% .
It would be nice to know if someone has this kind of problem and how they fix it.

```
❯ acpi -b
Battery 0: Discharging, 0%, rate information unavailable
Battery 1: Full, 100%
```

**Comment by BaronBaleron** [comment]
I have same problem. It shows up when i try reinstall TLP. Did you find aby solution?

**Comment by danger44** [comment]
> I have same problem. It shows up when i try reinstall TLP. Did you find any solution?

Sorry, the problem still persist even I have changed to POP OS. But battery backup is much better now.

**Comment by BaronBaleron** [comment]
I made some tests an i have best results with file firmware-5.bin_CNSS.TF.1.0-00267-QCATFSWPZ-1
from repo https://github.com/kvalo/ath10k-firmware/tree/master/QCA9377/hw1.0
just rename and replace file firmware-5.bin in /lib/firmware/ath10k/QCA9377/hw1.0

This from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/ath10k/QCA9377/hw1.0 was not so good for me but maybe will be better for someone.
