### ISSUE TITLE
Wifi No Longer Working

### ISSUE THREAD

**Issue by ndstate** [kfechter/LegionY530Ubuntu#107]
Hi,

I am running 5.8.0-63-generic #71~20.04.1. With Nvidia (465 other versions were not working) enabled the wifi card is no longer recognized.

lspci | grep -i realtek only shows the Ethernet card, not the wifi card:
08:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
lshw -C network doesn't list it either.

The bios is up-to-date

Thank you in advance for any help

**Comment by ndstate** [comment]
@kfechter I am sure you are busy and I appreciate your guide, but any insights? Thanks

**Comment by kfechter** [comment]
what about lspci | grep -i intel? 

Lenovo shipped these laptops with multiple vendors of wifi card, so its possible you don't have the realtek card.

**Comment by ndstate** [comment]
> what about lspci | grep -i intel?
> 
> Lenovo shipped these laptops with multiple vendors of wifi card, so its possible you don't have the realtek card.

Thanks for your reply @kfechter. I am certain it is a realtek card and wifi was actually working a day ago until I restarted. I believe it started working after some update. Worked fine all day, turned off my computer and no it doesn't even show up. This is crazy.

**Comment by kfechter** [comment]
interesting. Only thing I can think of at this point is the card failed. no idea why. Could always try re-seating the card. I've never seen one just disappear though.

**Comment by ndstate** [comment]
> interesting. Only thing I can think of at this point is the card failed. no idea why. Could always try re-seating the card. I've never seen one just disappear though.

It appears to be a kernel issue:

5.8.0-59-generic #66~20.04.1-Ubuntu: See's the wifi card, but it doesn't see any networks. Here is lspci:

07:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter (rev ff)
08:00.0 Ethernet controller: Re

5.8.0-63 no wifi card recognized

nvidia-driver-470 on both. Runs fine on 63, everything laggy on 59.

Whats odd is the wifi worked and connected on 63 previously. Any ideas on how to troubleshoot this? Thanks @kfechter

**Comment by ndstate** [comment]
To add more details. Rebooted to 5.8.0-63 with nvidia driver off. lspci now shows the realtek card, but following your tutorial I get:

rmmod: ERROR: Module r8822be is not currently loaded

But either way I need to go back to Nvidia driver enabled as everything is very laggy. Hope you dont mind me logging these issues here... in case someone else searches and finds this (maybe it will be helpful)

**Comment by kfechter** [comment]
Interesting. Kernel issues are the worst. seems like something regressed in an update. It's even more interesting that the nvidia driver seems to break the wifi, not sure what is going on there. Might be something to report on the ubuntu bug tracker.

**Comment by ndstate** [comment]
> Interesting. Kernel issues are the worst. seems like something regressed in an update. It's even more interesting that the nvidia driver seems to break the wifi, not sure what is going on there. Might be something to report on the ubuntu bug tracker.

Alright thanks. I will update if I figure something out - in case someone else runs into the same issue
