### ISSUE TITLE
Maybe a Tool for Custom Fan Control?

### ISSUE THREAD

**Issue by johnfanv2** [kfechter/LegionY530Ubuntu#110]
I created a tool for custom fan curves for Lenovo Legion 5, Legion 7 etc. It is called LenovoLegionLinux and is on github [https://github.com/johnfanv2/LenovoLegionLinux. ](https://github.com/johnfanv2/LenovoLegionLinux. )

Maybe it also works for the Y530 series. I saw that ExtremeCooling4Linux works with the Y530, which also works with Legion 5. So both probably will use the same embedded controller that is targeted by both tools.

If you want, you could try it. Because the Y530 is not yet in the list of compatible models, you have to use `sudo make forcereloadmodule` (see README). Then you could try it according to the README.

**Comment by kfechter** [comment]
I unfortunately don't have the Legion anymore

**Comment by popvladaurel** [comment]
I still use my Y530 on a daily basis, gonna give this a try when I get the time (might not be soon though...)
