### ISSUE TITLE
18.10 - freezes

### ISSUE THREAD

**Issue by Josemartins-ptc** [kfechter/LegionY530Ubuntu#12]
Following the tutorial.

After installing 18.10, when it boots it asks for username, I enter password, login and after that the machine freezes in a purple screen. Not even the mouse or track pad works....

Actually the first eyebrow movement was when clicking on restart after the installation finishes..but no restart happened. Had to use the power button. 

Disapointed.

**Comment by Josemartins-ptc** [comment]
Apparently the problem was because Intel Virtualization was enabled on the Bios. Disabling it made the ubuntu boot properly, however track pad seems to have erratic behaviors, and does not work occasionally/. With a mouse seems to work ok.

**Comment by kfechter** [comment]
for the freeze after installation, I got that too, rebooted using the magic SysRq combination. The freeze after login usually points to GPU configuration issues. Interesting that disabling VT-x fixes that. 

Currently running Windows while I finish my DotFiles, but I can try and figure out why it acts like that.

**Comment by Josemartins-ptc** [comment]
Track pad is OK now. I haven't done anything apart from the usual OS updates. So far no other problem, but battery disappears as fast as hell, just doing normal operations. Getting around 2.5 hours with a brand new machine doing normal operations, nothing heavy yet.

**Comment by kfechter** [comment]
I've noticed about the same battery life. configuring nvidia optimus and switching to Intel seems to help a bit, but its still not great. I have not tried configuring anything in TLP, which may help increase battery life some.
