### ISSUE TITLE
18.10 - No second screen

### ISSUE THREAD

**Issue by Josemartins-ptc** [kfechter/LegionY530Ubuntu#13]
Laptop seems to be working ok. But external hdmi screen is not detected.

**Comment by canmom** [comment]
For me, the external HDMI screen was clearly connected and could show a cursor but not any X windows if I dragged them over there.

I fixed this by changing the display manager to LightDM, [as described here](https://askubuntu.com/questions/829108/what-is-gdm3-kdm-lightdm-how-to-install-and-remove-them). Type

```
sudo apt-get install lightdm
```
in a console and select lightdm when prompted. There are various other options for a display manager, but I can confirm lightdm at least works with HDMI-out.

**Comment by Josemartins-ptc** [comment]
Well, I've tried, but no luck. As having external monitors is important for me, I reverted to 18.04 and it worked out of the box.
