### ISSUE TITLE
Ubuntu installation stuck

### ISSUE THREAD

**Issue by p1nox** [kfechter/LegionY530Ubuntu#18]
First of all, thanks so much for this guide! 💯 

Right after buying a `Lenovo Legion Y520`, I plug a pen drive with Ubuntu 18.04 and installed it formatting the whole disk, removing previous Windows installation, and not changing anything on Windows configuration, actually I didn't even log into Windows before installing Ubuntu.

So after installing Ubuntu it was working fine, but Nvidia drivers were not installed, so I restarted and disable `Secure Boot`, and then I installed Nvidia drivers, but for some reason after rebooting, there was an error, so I tried to reinstall ubuntu, and I'm having problems with grub2 installation, it gets stuck there, which might be related to any of these:

* https://ubuntuforums.org/showthread.php?t=2393377
* https://forums.lenovo.com/t5/Linux-Discussion/How-to-install-Linux-on-UEFI-systems-where-GRUB-fail-to-install/td-p/674103
* https://askubuntu.com/questions/1049167/failed-to-install-grub2-while-installing-ubuntu
* https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1734147?comments=all

I tried many things like:

* Complete installation connecting wifi and downloading everything extra, including drivers and such.
* Minimal installation, and erasing the whole disk letting wizard to setup partitions.
* Instead of selecting the option to erase the whole disk, I selected the option "Something Else", where I create two partitions, one for EFI and one for `/`.

Also, I tried installing Kali Linux, but the same happens getting stuck while installing grub2, and despite installation finishes eventually, when I login into the OS, it gets stuck opening some programs.

Any thoughts? Have you experienced something like that?

**Comment by p1nox** [comment]
I see warnings/errors like:

* `Warning: Source ID 24409 was not found when attempting to remove it GlLib.source_remove(self.timeout_id)`
* `ubuntu gvfsd-metadata[1980] g_dev_device_has_property: assertiong 'G_DEV_IS_DEVICE (device)' failed.`

**Comment by kfechter** [comment]
I have not experienced a hang when installing grub. I've had issues where the partitioner would hang unless I wiped the drives before starting.

**Comment by kfechter** [comment]
Does this issue persist with 19.04? Not sure what hardware differences between the Y520 and Y530 would cause your freezing issues. could also be some GPU weirdness. 19.04 improves the graphics stack for machines with nvidia GPUs.

**Comment by kfechter** [comment]
My guess is 16.04.1 and 18.04.1 are missing kernel fixes for the hardware. similar to the graphics issue with nouveau requiring modeset 0 to even get to desktop on some nvidia equipped machines.

Is it safe to mark this issue closed?

**Comment by p1nox** [comment]
Yes, please do, thanks for the help :).

**Comment by kfechter** [comment]
no prob!
