### ISSUE TITLE
After Setup (Power Control, Fan Control, CPU Temp Monitor)

### ISSUE THREAD

**Issue by rinn7e** [kfechter/LegionY530Ubuntu#4]
First of all, thank you very much, Kenneth, for a great and simple guide on setup with ubuntu. I just want to know if there are other programs that could be installed to control power, fan, monitor temperature etc... (Think of something similar to Lenovo Vantage on window)

**Comment by kfechter** [comment]
for low level power settings there is TLP. I can see if I can get some fan control and temp monitoring software working. 

Currently working on getting Some of the function keys working. In 18.10 live, the touchpad disable, camera privacy, mic mute, and airplane mode buttons all generate events. The screen record button appears to trigger an "unknown event" in dmesg.

**Comment by kfechter** [comment]
I found this guide for lm-sensors and pwmcontrol. I believe this setup allows automatic fan control. still looking for manual.

http://tuxtweaks.com/2008/08/how-to-control-fan-speeds-in-ubuntu/

**Comment by kfechter** [comment]
https://github.com/Maldela/fancontrol-gui

this is a fan control gui, but it seems to be for KDE, not the default gnome that "vanilla" installs of ubuntu desktop use

**Comment by kfechter** [comment]
I added a section to the guide for monitoring and fan control considerations. Closing this issue as resolved.
