### ISSUE TITLE
Get new images for Installing with secureboot on

### ISSUE THREAD

**Issue by kfechter** [kfechter/LegionY530Ubuntu#46]

**Comment by kfechter** [comment]
remove non secure boot steps

**Comment by kfechter** [comment]
Images added to InstallUbuntu Section

**Comment by liho00** [comment]
Is that ok to enable the secureboot on for installing the ubuntu 18.04.2 LTS? Beside the secureboot, is the fast boot need to disable also? May i know what is the boot order i need to set in order to install ubuntu 18.04.2 lts in legion y530. Thanks in advance!

**Comment by kfechter** [comment]
If you are going to be installing 18.04.2 I would follow the guide specifically for 18.04.2

https://github.com/kfechter/LegionY530Ubuntu/tree/18.04.2-Install-Guide

18.04.2 needs kernel/module changes to get things working, which doesnt play nicely with SecureBoot. other than secureboot I didn't change anything. you also shouldn't need to change the boot order. I think you only need to disable fastboot if you are dual booting the system. 

The guide shows how to boot the USB drive for install, so you shouldnt need to change the boot order.
