### ISSUE TITLE
ACPI Error when restarting

### ISSUE THREAD

**Issue by zopagaduanjr** [kfechter/LegionY530Ubuntu#53]
**Describe the bug**
I have tried to install Ubuntu(18.04) 3 times. First 2 times is Install without downloading, while the 3rd I tried to install while downloading updates. All the 3 installation where custom installation type (wherein I assign partition sizes to ROOT, SWAP, HOME). After Finishing installing, the reboot message pops up and I clicked reboot. Within the 3 installations I made, I always end up to this screen:

> 
![image](https://user-images.githubusercontent.com/38291023/55773471-48528180-5ac3-11e9-9094-309cea13b43b.png)

**To Reproduce**
My Y530 has
i5 - 8300H
1 TB
no M.2 secondary hdd
GTX 1050Ti

**Additional context**
have downloaded ubuntu 18.04 LTS image twice, etched my microsd card thrice for the three times i tried to install.
I'm using sandisk 32gb microsd as boot usb with a microsd to USB connector. Connected the usb at both left and right usb 3.1 ports of my y530.

**Comment by zopagaduanjr** [comment]
I tried it one last time but this time I updated my BIOS(8JCN50WW), Installed without downloading, then I also ended up on the same black screen as the picture above. I left it on overnight. On the next day, In the grub screen i Disable Nouveau Modeset, then the login screen shows.

**Comment by kfechter** [comment]
the ACPI error has to do with the PCI AER (Advanced Error Reporting)

that can be disabled with the boot flag pci=noaer 

for booting with nouveau, the nomodeset may be required (sometimes works), but that is stated in the guide under Additional Notes,

**Comment by zopagaduanjr** [comment]
after updating my nvidea card my ubuntu works fine without disabling Nouveau Modeset.
Been using ubuntu for 4 days and still working! thanks
