### ISSUE TITLE
I had problem that i cannot flash the image into my pendrive!

### ISSUE THREAD

**Issue by liho00** [kfechter/LegionY530Ubuntu#56]
I had problem that i cannot flash the image into my pendrive!

![image](https://user-images.githubusercontent.com/34411102/56879251-73107400-6a8a-11e9-89bd-507597f352ad.png)

**Comment by liho00** [comment]
Now, my pendrive only left 2mb. How do i restore back?
![image](https://user-images.githubusercontent.com/34411102/56879385-13ff2f00-6a8b-11e9-81ac-5883521d4d81.png)

**Comment by liho00** [comment]
Solved, is the pendrive itself's problem. Change a new pendrive will do.

**Comment by kfechter** [comment]
Yeah, flash drives can be finicky. I have a few sandisks that exhibit this issue. sometimes even when this happens, the flash drive will still work.
