### ISSUE TITLE
bios storage boot option control AHCI or RST mode

### ISSUE THREAD

**Issue by liho00** [kfechter/LegionY530Ubuntu#57]
Which bios storage boot option control is better AHCI or RST. 
Is ubuntu can installed with RST mode? 
My laptop has c drive - 128gb ssd and d drive - 1tb hdd. 
Thanks in advance for advise.

**Comment by kfechter** [comment]
Unless the SSD is optane, the machine comes set in AHCI mode. 

Linux doesn't particularly support Intel RST and its really only useful for Optane or FakeRAID.
