### ISSUE TITLE
Fan not working in linux ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by liho00** [kfechter/LegionY530Ubuntu#58]
How to control my fan when using ubuntu 18.04.2 lts, my model is Lenovo legion y530?

And when i run the lm-sensors, there is not showing my fan info, but my laptop had 2 fans.

Because when i running ubuntu, its temperature of the core is up to 60+ °C

![Screenshot from 2019-05-03 12-19-59](https://user-images.githubusercontent.com/34411102/57122179-926f1000-6dae-11e9-8b74-db2b671e0bd9.png)
![Screenshot from 2019-05-03 13-43-58](https://user-images.githubusercontent.com/34411102/57122181-9864f100-6dae-11e9-97ce-a4d48defc9c3.png)

**Comment by kfechter** [comment]
Can you hear the fans spinning at all? On my Y530 running 18.04.2 the fans would still spin up randomly as they do on windows.

seems strange that its not detecting the pwm sensors. As a last resort, you could try running a live usb of  19.04 and seeing if pwm works there.

**Comment by liho00** [comment]
I do know how to control fan in ubuntu, just press fn + q

**Comment by joaomamede** [comment]
This app solves the problem. You can max the fans at will:

https://odintdh.itch.io/extremecooling4linux
