### ISSUE TITLE
Running Ubuntu is draining the battery very fast

### ISSUE THREAD

**Issue by liho00** [kfechter/LegionY530Ubuntu#61]
Im just using google chrome in ubuntu, my battery will be drained about 3 times faster than im using google chrome in windows 10.

For example, running google chrome in ubuntu took 1 hr 15 min to completely drained the battery but running google chrome in windows 10 took about 4 hr.. 

How to solve this issues, as i installed tlp in ubuntu.

**Comment by kfechter** [comment]
Do you have the nvidia drivers/ nvidia-prime packages installed. 

does the command ` prime-select query` return output? If not, the machine will constantly be running the nvidia GPU and the nvidia gpu will give between 1 and 1.5 hours of battery life.

**Comment by liho00** [comment]
the returned out was NVIDIA

**Comment by liho00** [comment]
Okay, i switch it back to intel using `sudo prime-select intel `, let me observe the battery life and usage.

**Comment by kfechter** [comment]
I would do a reboot after the prime select just to be safe. Sometimes it doesnt always switch immediately

**Comment by liho00** [comment]
Yes, i did a reboot. But what is the correct way of install TLP, is using this command? `sudo apt install -y tlp tlp-rdw`, as im new to ubuntu, not quite sure how to setup tlp.

**Comment by kfechter** [comment]
Yeah. That is correct. I've installed tlp, but I've never really figured out how to configure it.

**Comment by kfechter** [comment]
what is the output of the following command `cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor

`

**Comment by liho00** [comment]
Sudo prime-select intel will retain battery life, thank you @kfechter

**Comment by dush1729** [comment]
@liho00 after using the given command, my external monitor is not detected. Please help.

**Comment by kfechter** [comment]
In intel mode, you cannot use external monitors. Only in nvidia mode as the display outputs are attached to the nvidia gpu

**Comment by dush1729** [comment]
@kfechter thanks for the quick response. Now the issue I'm facing is if I revert back to `prime-select nvidia` then I get blank screen after login and if I use `prime-select intel` then I'm able to login and change brightness but same external display issue exists in this mode.

**Comment by dush1729** [comment]
I'm facing this issue Lenovo legion Y540 with Nvidia rtx 2060 graphics.

**Comment by kfechter** [comment]
Interesting. Now I'm wondering if the drivers dont fully support the RTX 20 series. I dont have any machines that I can test this on unfortunately.
