### ISSUE TITLE
HDMI audio device

### ISSUE THREAD

**Issue by crazieNephilim** [kfechter/LegionY530Ubuntu#62]
Hi, after I connect my TV with HDMI, there is no audio output to tv, and audio device (SAMSUNG TV) is not listed. I tried to kill audio pulse, and tried to install audio pulse GUI, still no audio device

**Comment by kfechter** [comment]
under audio settings, is the HDMI audio device listed?

**Comment by crazieNephilim** [comment]
Nope

**Comment by kfechter** [comment]
hmm. Are you using prime packages or the nouveau driver?

**Comment by crazieNephilim** [comment]
Prime packages

**Comment by kfechter** [comment]
I'll have to look into it. I've not tried using HDMI audio on the laptop. Are you on 18.04.x or 19.04?

**Comment by crazieNephilim** [comment]
18.04.02

**Comment by kfechter** [comment]
ok, I'll try installing 18.04.2 when I have a chance.

**Comment by kfechter** [comment]
I confirmed that it does not work on 18.04.2 installing this module seems to have gotten it working. It's a bit manual since you have to modprobe it and set it to on, but after following the read me hdmi audio was working. I will now try it with 19.04

https://github.com/hhfeuer/nvhda

**Comment by crazieNephilim** [comment]
Thanks
