### ISSUE TITLE
HDMI, Kubuntu 18.04.02, Intel

### ISSUE THREAD

**Issue by yshinkarev** [kfechter/LegionY530Ubuntu#64]
I have next components: nvidia 390.116 + [nvhda](https://github.com/hhfeuer/nvhda)
If I using nvidia as primary video card, all works perfectly.
I connect external monitor by HDMI and output audio to HDMI too. Works.
Can I use Intel as primary video card and use external monitor to output video/audio to HDMI?
If I set `sudo prime-select intel` and connect external monitor by HDMI, I have tooltip "No external monitor" and xrandr output me only eDP.

**Comment by kfechter** [comment]
the Display outputs (minus the internal display) are connected to the nvidia card in an optimus setup. Unfortunately, there is no way on current optimus equipped laptops to use the intel card while retaining use of HDMI, DisplayPort, etc.

**Comment by yshinkarev** [comment]
Sad, thanks.
