### ISSUE TITLE
Evaluate other distros that aren't Ubuntu

### ISSUE THREAD

**Issue by kfechter** [kfechter/LegionY530Ubuntu#65]
With Canonical's decision to stop supporting/updating i386 packages going forward, It may not be wise to continue updating this guide for Ubuntu LTS versions. 19.10 and beyond will no longer provide updated i386 architecture packages. this breaks many games and other applications that only provide 32 bit executables. 

This issue will serve as a place to put any ideas or discussions.

**Comment by jacksummers** [comment]
Hey man thanks for the guide, I have successfully installed pop os with windows 10 dual boot in my legion. Do u have the optane working successfully with a working dual boot? I had to change a few things with your guide and accommodate some of the things I learned via trial and error. To even allow dual boot, I had to change from rst to ahci. I had it install once before changing anything in bios, but it was running windows dreadfully slow so I had to make some changes. Still cannot get optane working on windows, I don't think it will as its ahci now, but it is working pretty normal just with my 16gb ram; it is worth mentioning the latest pop OS has everything working out of the box for our device.

**Comment by kfechter** [comment]
My machine doesn't have optane unfortunately. 

from what I know, Optane isn't supported on Ubuntu at all. however, you can do some command line stuff (I believe that's in the troubleshooting), that will allow you to dual boot while retaining optane on windows. 

Instead of selecting "Install Ubuntu," select the "Try Ubuntu" option. Then open a terminal and issue the following command

sudo dmraid -E -r /dev/sda

It will ask if you want to delete metadata, you can say yes to this.

You can now exit the terminal and follow the guide to install Ubuntu in a dualboot scenario

the alternative is replacing either the optane drive OR the hard drive with a larger SSD.

**Comment by redines** [comment]
Has anyone tried Linux mint or arch distros like manjaro?
Interested in these and will try to get linux mint working on my legion soon.

**Comment by kfechter** [comment]
I have not tried mint. since its Ubuntu/Debian based, should be relatively similar. I haven't had a chance to try much of anything since I'm in the middle of moving and most of my stuff is packed up. 

I can try a few distros when I have some time. I want to keep the guide as simple as possible, because adding a bunch of different distros/configurations to the mix is just asking for trouble

**Comment by kfechter** [comment]
side note: looks like they may have backtracked slightly on the i386 decision

**Comment by kfechter** [comment]
I think I am going to table other distros for now and switch to only supporting LTS releases now that 18.04.3 LTS has all the fixes that 19.04 brought in.
