### ISSUE TITLE
Bios update in dual boot legion y530

### ISSUE THREAD

**Issue by liho98** [kfechter/LegionY530Ubuntu#67]
1. Has anyone tried to update the BIOS in the Legion Y530 dual boot system?
2. Does it cause any problems?
3. Does it is safe to update the BIOS with the legion y530 run windows alongside with Ubuntu.

Thanks in advance!

**Comment by kfechter** [comment]
I have not, but it shouldn't cause any issues as long as the update doesn't change your settings.

**Comment by VladimirMikulic** [comment]
@liho98 I did. It didn't cause any problems.
BIOS Upadte Version: 8JCN52WW

**Comment by liho00** [comment]
Damn, after I upgraded the BIOS, the grub boot loader is no longer displayed.

**Comment by liho98** [comment]
the solution is to change the boot priority from windows boot manager to ubuntu efi boot manager - Grub 2.
