### ISSUE TITLE
screen backlight not working

### ISSUE THREAD

**Issue by IslamAssem** [kfechter/LegionY530Ubuntu#69]
Hi 
i had tried to install linux distribution but not ubuntu but kali linux and everything was going well and i had windows installed on ssd so i decided to install windows on hdd but in last step where i was asked to force grup boot loader and i selected no and it finished everything and restarted and once it restarted screen backlignt weren't working i don't know why i tried to remove kali and not working and tried to install new windows and not working too,i tried to download latest bios update and not working screen backlight not working at all even  in bios or boot menu
if you have any sugesstions please help me

**Comment by kfechter** [comment]
By backlight not working, do you mean the screen is completely black, or do you mean that adjustment of the backlight doesnt work?

**Comment by PrabhanshuAttri** [comment]
I am unable to change the brightness. @IslamAssem might be talking about brightness adjustment. I tried many solutions. No luck.

**Comment by dush1729** [comment]
I'm facing the same issue. You can resolve it by changing the driver in softwares and updates to open source driver. But this will create another issue. You won't be able to attach external monitor. Is there any way to fix both issues?

**Comment by dush1729** [comment]
Hi, I've finally got a fix for my brightness issue. Just follow what's written here - [https://askubuntu.com/a/199652/1012471](https://askubuntu.com/a/199652/1012471)

Works for my Lenovo Legion Y540

**Comment by PrabhanshuAttri** [comment]
@dush1729 Could you explain the software update part a bit? The solution on the link you shared doesn't work for me. It hangs after login

**Comment by dush1729** [comment]
Open Software & Updates, then select Additional Driver. Select nvidia 430 driver. 430 works for me(my graphics card is nvidia rtx 2060)

![Screenshot from 2019-11-04 22-51-05](https://user-images.githubusercontent.com/13865613/68142605-c7267480-ff55-11e9-847b-690eaed4289e.png)

**Comment by dush1729** [comment]
@PrabhanshuAttri If this doesn't work, try upgrading the BIOS. Lenovo released a BIOS update few days back. You can find it here - [https://support.lenovo.com/in/en/downloads/ds539700](https://support.lenovo.com/in/en/downloads/ds539700). These are the only 3 steps I did to fix issues related to display.

1. Changing driver to Nvidia 430
2. That ask ubuntu answer I mentioned above
3. BIOS update

**Comment by dirodriguezm** [comment]
@dush1729 I tried changing the driver in softwares and updates but I don't have an open source driver. Then tried creating a .conf file as described in the askubuntu answer and didn't work. Then updated the BIOS and still haven't been able to change brightness.

One intresting thing is that brightness settings work on ubuntu live usb, but not after installing it. Probably the nvidia driver is causing the problem.

**Comment by PrabhanshuAttri** [comment]
@dush1729 I did update BIOS and I am using Nvidia 430. The answer in ubuntu forums shows me a black screen.
Currently, I am using [Brightness controller](https://github.com/lordamit/Brightness). This workaround requires manually setting brightness with each reboot.

**Comment by sauravsolanki** [comment]
This will be mostly driver issue. Try changing driver. This fix my problem.

![Screenshot from 2021-06-13 00-21-13](https://user-images.githubusercontent.com/22391954/121786454-6fde9080-cbdd-11eb-9df7-8a1aa47a0e27.png)
