### ISSUE TITLE
HDMI not working on clean install 

### ISSUE THREAD

**Issue by KilroyMcK** [kfechter/LegionY530Ubuntu#72]
I decided to install ubuntu 19.04 on my y530 and after following the provided tutorial the hdmi worked. Then I installed Kubuntu, whicht didn't work at all. Then I installed Ubuntu again and now the HDMI doesn't work. 

I tried the steps provided in the troubleshooting section and in other issue-threads, no luck. both monitor and cable still work properly. 

 -Ubuntu 19.04
 -Kernel version 5.0.0-25-generic

**Comment by kfechter** [comment]
Interesting. What is the output of prime-select query?

**Comment by dush1729** [comment]
1. Goto Software and Updates.
2. Select additional drivers.
3. Install the proprietary nvidia driver.

This fixes the issues. But creates another issue. You cannot change brightness now. Please help if you find a fix for this.

**Comment by 610th** [comment]
I have the same issue with 18.04. Can't get HDMI not DP to work. Any ideas?

`sith@legion:~$ prime-select query
nvidia
sith@legion:~$ uname -a
Linux legion 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kfechter** [comment]
@610th Are you running 18.04.3 or 18.04.1? the #31~18.04.1-Ubuntu suggests that its not the newest 18.04, which has a bunch of fixes but that could just be a different version number from somewhere.

Also, is your machine the Y530 or one of the newer models?

**Comment by 610th** [comment]
Ah, sorry for leaving that part out. I'm running 18.04.3 (Kubuntu).

I'm running a (~1 year old?) Y530-15ICH.

**Comment by kfechter** [comment]
Interesting. 

Debugging these issues is a bit hard. I'm currently running Ubuntu with gnome.  Do you know if Kubuntu is using Wayland or Mir?

**Comment by 610th** [comment]
I agree. I've been debugging this kind of stuff too many times. :-) Hoped for an easy solution. Pew.. And I'm not running Wayland.

**Comment by dush1729** [comment]
@610th try upgrading the bios - https://pcsupport.lenovo.com/in/en/products/laptops-and-netbooks/legion-series/legion-y530-15ich/downloads/ds503758

I faced the same issue issue in Lenovo Legion Y540 but fixed it by changing graphic driver to proprietary

**Comment by 610th** [comment]
@dush1729 I did that just before installing Kubuntu. I think this might be related to secure boot.

From dmesg:
```
[   12.976608] input: HDA NVidia HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input29
[   12.976741] input: HDA NVidia HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input30
[   12.977674] input: HDA NVidia HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:01.0/0000:01:00.1/sound/card1/input31
[   12.984365] iwlwifi 0000:00:14.3: BIOS contains WGDS but no WRDS
[   13.035480] Lockdown: Xorg: ioperm is restricted; see man kernel_lockdown.7
[   13.166838] PKCS#7 signature not signed with a trusted key
[   13.245878] PKCS#7 signature not signed with a trusted key
```
```
sith@legion:~$ sudo lshw -C display
[sudo] password for sith: 
  *-display UNCLAIMED       
       description: VGA compatible controller
       product: GP107M [GeForce GTX 1050 Ti Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list
       configuration: latency=0
       resources: memory:a3000000-a3ffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:4000(size=128) memory:a4080000-a40fffff
  *-display
       description: VGA compatible controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:129 memory:a2000000-a2ffffff memory:b0000000-bfffffff ioport:5000(size=64) memory:c0000-dffff
```

**Comment by kfechter** [comment]
Ah, yeah SecureBoot screws things up even though it should work fine on Ubuntu 18.04 and up

**Comment by dush1729** [comment]
Yes secure boot disabled  and fast startup in windows disabled are a must for dual boot. Glad you found the fix. I hope I will fix my brightness issue someday. :( My screen always remain on 100% brightness.

**Comment by dush1729** [comment]
Hi, I've finally got a fix for my brightness issue. Just follow what's written here - [https://askubuntu.com/a/199652/1012471](https://askubuntu.com/a/199652/1012471)

Works for my Lenovo Legion Y540
