### ISSUE TITLE
Invalid link in NvidiaConfig.md

### ISSUE THREAD

**Issue by VladimirMikulic** [kfechter/LegionY530Ubuntu#73]
At the bottom of the NvidiaConfig.md file, there is a link to "Advanced Features Guide" (Advanced.md), but the file appears to be missing.

Where can I find "advanced features", or this is just a mistake?

**Comment by kfechter** [comment]
I probably borked something when Updating the guide

**Comment by kfechter** [comment]
should be fixed now.
