### ISSUE TITLE
18.04 doesn't install drivers properly

### ISSUE THREAD

**Issue by kfechter** [kfechter/LegionY530Ubuntu#75]
Update the guide to re-add the GPU configuration stuff because 18.04 doesnt seem to install the GPU drivers properly.

**Comment by krigga** [comment]
Can this be related to my freshly installed kubuntu freezing after reboot and logging in?

**Comment by kfechter** [comment]
Yep, that is it!

the fix is to boot with the nouveau.modeset=0, then installing the nvidia driver through the additional drivers tab of software sources settings.

**Comment by kfechter** [comment]
I need to update the guide to add this. 

Hopefully its fixed in 20.04

**Comment by krigga** [comment]
![Screenshot_20191003_190551](https://user-images.githubusercontent.com/25533192/66144065-da6db980-e610-11e9-8921-4cdee1ed0540.png)
is that the window I'm looking for?

**Comment by kfechter** [comment]
Yeah, that's the one.

**Comment by krigga** [comment]
Thank you for your help, sorry for possibly off topic

**Comment by kfechter** [comment]
No problem. It's not off topic at all. 

This is just a tracking issue for me updating the guide to include the fix for this problem, however your issue is 100% relevant so it belongs here.

**Comment by kfechter** [comment]
Looks like this is possibly related to SecureBoot being enabled.
