### ISSUE TITLE
Grub not loading in windows 10

### ISSUE THREAD

**Issue by URAJUV** [kfechter/LegionY530Ubuntu#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Info (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Kernel version [output of uname -r]

**Additional context**

**Comment by kfechter** [comment]
By grub not loading in windows 10 do you mean that grub doesn't appear in the windows bootloader? 

not really sure what you mean since the issue template just has all the default information and nothing specific about your system

**Comment by URAJUV** [comment]
Yes, grub does not appear in windows bootloader.
I have to raise a pull request for this:--
https://github.com/URAJUV/LegionY530Ubuntu/blob/master/Images/os_optimization.png
https://github.com/URAJUV/LegionY530Ubuntu/blob/master/Sections/Troubleshooting.md

Will put it in proper format and request review.

**Comment by kfechter** [comment]
Alright, I'll get that merged in when it's ready.
