### ISSUE TITLE
Ubuntu 18.04 installer did not detect windows boot manager

### ISSUE THREAD

**Issue by ignatiusrdp** [kfechter/LegionY530Ubuntu#81]
**Describe the bug**
So i tried to install ubuntu on my legion, already followed the instructions but the installer didnt detect it

**Expected behavior**
![image](https://user-images.githubusercontent.com/36185403/73813272-18bef380-4812-11ea-91f5-cb6b35b0e231.png)

**What i got**
![19983](https://user-images.githubusercontent.com/36185403/73813344-4441de00-4812-11ea-80ce-f58e0ded4e91.jpg)

 - OS: Ubuntu 18.04

**Comment by kfechter** [comment]
interesting, that's the advanced partitioner. not sure why the installation is immediately going there. 

Do you have an optane equipped model?

**Comment by ignatiusrdp** [comment]
yes i have the optane model, maybe thats the problem?

**Comment by kfechter** [comment]
In an Admin Powershell, run the command Get-PhysicalDisk

That will tell you whether or not you have optane

**Comment by kfechter** [comment]
If you have optane, this issue might help

https://github.com/kfechter/LegionY530Ubuntu/issues/25#issuecomment-474199626

**Comment by ignatiusrdp** [comment]
ok ill try it this weekends because i have some college stuff, thanks i will report if it works

**Comment by ignatiusrdp** [comment]
Hey man it worked and i got it installed but it seems now i cant boot to my windows. Currently im stuck on repairing mode, tried some stuff but didn't  work

**Comment by kfechter** [comment]
In Ubuntu, can you screenshot what the partition tables of the available disks in Gparted look like. I'm not well-versed in the nuances of dual booting, as I've never had good experiences getting dual boot working properly.

**Comment by ignatiusrdp** [comment]
Gparted show errors too, i can't screenshot because i decided to reinstall my windows os and delete ubuntu. Might try this again with my seniors later, thank you for the help dude.
