### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ndstate** [kfechter/LegionY530Ubuntu#88]
Hi,

The Ubuntu 20.04 beta is out now. Do you anticipate these steps will work with 20.04... or will you be creating a new guide?

Thanks!

**Comment by kfechter** [comment]
I will be updating the guide links when 20.04 is out, there is currently a branch for these changes.

I don't anticipate much change between 18.04 and 20.04, if anything, some steps may be able to be removed if things are fixed. I'll probably do some testing before I merge the guide to master

**Comment by ndstate** [comment]
Awesome! Thanks so much for your great work.

**Comment by kfechter** [comment]
No problem.

**Comment by kfechter** [comment]
Guide is updated for 20.04, marking this issue closed.
