### ISSUE TITLE
Ubuntu 20.04 LTS - Second monitor doesn't work

### ISSUE THREAD

**Issue by dergachovda** [kfechter/LegionY530Ubuntu#96]
After installation Ubuntu 20.04 the second monitor doesn't work.
On Ubuntu 18.04 it's working.

**Comment by kfechter** [comment]
What is the output of `prime-select query`?

**Comment by dergachovda** [comment]
```
$ sudo prime-select query
nvidia

$ hostnamectl
   Static hostname: *********
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ******************
           Boot ID: *******************
  Operating System: Ubuntu 20.04 LTS
            Kernel: Linux 5.4.0-26-generic
      Architecture: x86-64
```

![Screenshot from 2020-04-26 22-38-14](https://user-images.githubusercontent.com/13643478/80317822-ac4f0180-880e-11ea-853b-6ae41bcfe67c.png)

**Comment by dergachovda** [comment]
Resolved! Changing nvidia-driver version was helped me.

![Screenshot from 2020-04-26 23-38-19](https://user-images.githubusercontent.com/13643478/80319082-2be0ce80-8817-11ea-819f-7c53e6810925.png)
