### ISSUE TITLE
Nvidia card not visible on 20.04

### ISSUE THREAD

**Issue by matdurand** [kfechter/LegionY530Ubuntu#98]
**Describe the bug**
I just upgraded to 20.04 (from 19.10) and my Nvidia card doesn't seem to exist anymore. It was working fine on 19.10.

**To Reproduce**
1. Upgrade to 20.04 from 19.10

**Expected behavior**
I should be able to see the nvidia card using the following commands:
```
>ubuntu-drivers devices  
== /sys/devices/pci0000:00/0000:00:14.3 ==
modalias : pci:v000...
vendor   : Intel Corporation
model    : Wireless-AC 9560 [Jefferson Peak]
manual_install: True
driver   : backport-iwlwifi-dkms - distro free
```
```
>lshw -c display
  *-display                 
       description: VGA compatible controller
       product: UHD Graphics 630 (Mobile)
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:156 memory:a2000000-a2ffffff memory:b0000000-bfffffff ioport:5000(size=64) memory:c0000-dffff
```
```
>lsmod | grep nvidia
no output
```
prime-select doesn't give me any error when I try to switch between intel and nvidia.

**System Info (please complete the following information):**
- Lenovo Legion Y530-15ICH 
- OS: Ubuntu 20.04
- Kernel version Kernel: Linux 5.4.0-29-generic

**Comment by kfechter** [comment]
It's possible that the in-place upgrade to 20.04 borked something. is there an nvidia driver listed in the Drivers section of the software sources settings. 

![image](https://user-images.githubusercontent.com/4164101/82287704-d3f93b80-996e-11ea-8587-98b3be6d6ed8.png)

should look somewhat similar to the above screenshot.

**Comment by kfechter** [comment]
It may have updated the driver to a 440, which was having some other issues. Try the 435 driver as that one appears to work better at the time of writing

**Comment by matdurand** [comment]
The `ubuntu-drivers` command gives the same results as the Additional Drivers tab in the UI. I only see the wifi card there, and  the mention at the bottom says "No proprietary driver in use".

I tried removing the 440 drivers and reinstalling the 435 using `apt`, but it doesn't make the nvidia card appear  when using `lshw -c display`. 

Any other ideas?

**Comment by matdurand** [comment]
I just did a quick test and booted a fresh Ubuntu 20.04 from a usb stick (using nomodeset) and the Nvidia card is there in the additional drivers tab like in your screenshot.

It's a shame, because it means that something went wrong with the upgrade and now I'm gonna have to perform a fresh install.

**Comment by kfechter** [comment]
Interesting. I've personally never had an in-place upgrade work as it is intended to. Something always seems to break when I do it.

**Comment by matdurand** [comment]
I went with a fresh install and the Nvidia card is visible now.

One thing was weird though, using the in-place upgraded version of ubuntu 20.04 where the nvidia card was not visible, I had better battery life and lower average CPU temperature compared to my new fresh install using the intel card (`prime-select intel`). I did not use it for long so maybe it was just a coincidence...

**Comment by kfechter** [comment]
It's possible that the card was completely powered off. sometimes optimus can get into weird states. However, you generally only see the fully powered off state for laptops configured with MUXed GPUs. the Legion has a MUXless optimus setup (no dedicated hardware chip for switching the GPU input/output).

regardless, I have added a section to the troubleshooting regarding in-place upgrades breaking the switching GPU config.
